# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "vmw_pvscsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5c0ce2ae-c3b7-4fa1-931f-697e7a849f0b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9A1C-1BBF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkForce false;

  networking = {
    interfaces.ens192 = {
      ipv6.addresses = [{
        address = "2a0d:6c2:6:282::";
        prefixLength = 47;
      }];
      ipv4.addresses = [{
        address = "193.46.218.44";
        prefixLength = 24;
      }];
    };
    defaultGateway = {
      address = "193.46.218.1";
      interface = "ens192";
    };
    defaultGateway6 = {
      address = "fe80::1";
      interface = "2a0d:6c2:6::1";
    };
  };


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
