name: Updater

on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:   
  update_flake:
    runs-on: ubuntu-node
    steps:
    - name: Set up git
      run: |
        git config --global user.email "github-actions[bot]"
        git config --global user.name "actions[bot]"
        git config --global http.sslVerify "false"
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ssh-strict: false
    - name: update flake
      run: nix flake update
    - name: Commit and push
      run: |
        if git diff --exit-code; then
          echo "Found no changes"
          exit 0
        fi
        git add .
        git commit -m "flake.lock: Update"
        git push
