#!/usr/bin/env python
import sys
import os
import tempfile
import re

tmp=tempfile.mkstemp()

with open(sys.argv[3]) as fd1, open(tmp[1],'w') as fd2:
    for line in fd1:
        line = re.sub(sys.argv[1],sys.argv[2], line)
        fd2.write(line)

os.rename(tmp[1],sys.argv[3])
