import = [
  "~/.config/alacritty/keys.toml",
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]
shell = "/opt/homebrew/bin/fish"
working_directory = "/Users/kron"

[bell]
animation = "EaseOutExpo"
duration = 0

# https://github.com/ribru17/bamboo.nvim/blob/master/extras/alacritty/bamboo_multiplex.toml
# # Default colors
# [colors.primary]
# background = '0x232923'
# foreground = '0xece1c0'
#
# # Normal colors
# [colors.normal]
# black = '0x171f17'
# red = '0xdc4f62'
# green = '0x81af58'
# yellow = '0xceba49'
# blue = '0x409cdc'
# magenta = '0xa09af8'
# cyan = '0x68baae'
# white = '0xece1c0'
#
# # Bright colors
# [colors.bright]
# black = '0x5a5e5a'
# red = '0xdc4f62'
# green = '0x81af58'
# yellow = '0xceba49'
# blue = '0x409cdc'
# magenta = '0xa09af8'
# cyan = '0x68baae'
# white = '0xfff8f0'

# https://github.com/ribru17/bamboo.nvim/blob/master/extras/alacritty/bamboo.toml
# Default colors
[colors.primary]
background = '0x252623'
foreground = '0xf1e9d2'

# Normal colors
[colors.normal]
black = '0x1c1e1b'
red = '0xe75a7c'
green = '0x8fb573'
yellow = '0xdbb651'
blue = '0x57a5e5'
magenta = '0xaaaaff'
cyan = '0x70c2be'
white = '0xf1e9d2'

# Bright colors
[colors.bright]
black = '0x5b5e5a'
red = '0xe75a7c'
green = '0x8fb573'
yellow = '0xdbb651'
blue = '0x57a5e5'
magenta = '0xaaaaff'
cyan = '0x70c2be'
white = '0xfff8f0'


[cursor]
blink_interval = 500
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
# opacity = 0.85
# blur = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 2
y = 2

[terminal]
osc52 = "CopyPaste"

